name: Acceptance - AI Generate Result

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ai-generate-result:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      TEST_BASE_URL: http://localhost:3000
      MOCK_AI: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run start &
      - name: Wait for server
        run: |
          for i in {1..90}; do
            if curl -fsS http://localhost:3000/ > /dev/null; then
              echo "Server is up"; exit 0; fi; sleep 1; done
          echo "Server failed to start"; exit 1
      - run: npm run migrate:quiz_sessions_cache || echo 'Skipping migration apply (RPC helper not present)'
      - run: npm run seed:happy
      - run: npm run ci:accept:ai
