name: Acceptance - AI Generate Result

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  ai-generate-result:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      TEST_BASE_URL: http://localhost:3000
      MOCK_AI: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start app
        run: npm run start &

      - name: Wait for server
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:3000/ > /dev/null; then
              echo "Server is up"; exit 0; fi; sleep 1; done
          echo "Server failed to start"; exit 1

      - name: Apply migration (quiz_sessions columns + cache)
        run: |
          npm run migrate:quiz_sessions_cache || echo "Skipping migration apply (RPC helper not present)"

      - name: Seed happy path
        run: npm run seed:happy

      - name: Run acceptance tests (mock AI)
        run: npm run ci:accept:ai
